---
title: "model result"
author: "Sky"
date: "2022/6/27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

```{r read exp data}
# p <- readRDS("simulation/data/p.rds")
# p <- distinct(p)
# p$type<-str_extract(p$ID,"\\D+")
# write.csv(p,"../data/new_exp/summary_painting.csv",row.names = F)
p <- read.csv("../data/new_exp/summary_painting.csv")

# p <-  p %>% filter(type=="L")## test on low risk group first
pms <- p %>% group_by(type) %>% summarise_at(vars(OB_1:performance), list(mean = mean, sd = sd))
```



```{r simu data from many groups}
dt_name = c("HL","LH","H","L","L")
data.list = list()
allresult <- read.csv("../data//model_exp_nofamexp/test/Hc/all_dwsch_added.csv")
allresult$type = "Hc"
for (i in 1:length(dt_name)){
  dt <- read.csv(paste0("../data/model_exp_nofamexp/test/",dt_name[i],"/all_dwsch_added.csv"))

  dt$type = dt_name[i]
  dt$afterbreak = as.factor(dt$afterbreak)
  data.list[[i]] <- dt%>% group_by(Subject,afterbreak,type) %>%
  summarise_at(vars(Schema_RT:performance,dwellmean_1:dwellmean_4),mean,na.rm=TRUE)
  allresult <- rbind(allresult,dt)
}

allresult <- allresult %>% select("Subject","Round","RT_1","RT_2","RT_3","RT_4","OB_1","OB_2","OB_3","OB_4","AS_1","AS_2","AS_3","AS_4","dwellmean_1","dwellmean_2","dwellmean_3","dwellmean_4","schema_payoff","AC","performance","type","novelty","afterbreak","breakR")
colnames(allresult) <- c("ID","Round","RT_1","RT_2","RT_3","RT_4","OB_1","OB_2","OB_3","OB_4","AS_1","AS_2","AS_3","AS_4","dwmean_1","dwmean_2","dwmean_3","dwmean_4","payoff","accuracy","performance","type","novelty","afterbreak","breakR")
```


```{r reaction time all}
## get mean and sd
mdn <- allresult %>% group_by(afterbreak,novelty) %>% summarise_at(vars(RT_1:performance), list(mean = mean, sd = sd))
## change wide to long for ploting
mn <- mdn %>% pivot_longer(RT_1_mean:RT_4_mean,names_to = "RT_phase",values_to = "RT_mean") %>%
  select(RT_phase,RT_mean,novelty,afterbreak) %>% mutate(RT_phase=str_extract(RT_phase,pattern = "\\w{2}_\\d"))
## same for sd and merge them  
mnl <- mdn %>% pivot_longer(RT_1_sd:RT_4_sd,names_to = "RT_phase",values_to = "RT_sd") %>%
  select(RT_phase,RT_sd,novelty,afterbreak) %>% mutate(RT_phase=str_extract(RT_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(mn,by=c("novelty","afterbreak","RT_phase"))
## convert col type so that can do rbind later
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")
## do the same for paintings
pmsn <- p %>% group_by(afterbreak,novelty) %>% summarise_at(vars(OB_1:performance), list(mean = mean, sd = sd))
en <- pmsn %>% pivot_longer(RT_1_mean:RT_4_mean,names_to = "RT_phase",values_to = "RT_mean") %>%
  select(RT_phase,RT_mean,novelty,afterbreak) %>% mutate(RT_phase=str_extract(RT_phase,pattern = "\\w{2}_\\d"))
enl <- pmsn %>% pivot_longer(RT_1_sd:RT_4_sd,names_to = "RT_phase",values_to = "RT_sd") %>%
  select(RT_phase,RT_sd,novelty,afterbreak) %>% mutate(RT_phase=str_extract(RT_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(en,by=c("novelty","afterbreak","RT_phase"))
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")

## merge the exp and model result
enl$type2 = 'exp'
mnl$type2 = 'model'
allrt = rbind(enl,mnl)

## regardless of type
ggplot(allrt,aes(x=RT_phase,y=RT_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=RT_mean-RT_sd,ymax=RT_mean+RT_sd))+facet_grid(afterbreak~type2)+
  theme_minimal()+labs(title="Experimental vs Model result")
```


```{r ob}
mn <- mdn %>% pivot_longer(OB_1_mean:OB_4_mean,names_to = "OB_phase",values_to = "OB_mean") %>%
  select(OB_phase,OB_mean,novelty,afterbreak) %>% mutate(OB_phase=str_extract(OB_phase,pattern = "\\w{2}_\\d"))
  
mnl <- mdn %>% pivot_longer(OB_1_sd:OB_4_sd,names_to = "OB_phase",values_to = "OB_sd") %>%
  select(OB_phase,OB_sd,novelty,afterbreak) %>% mutate(OB_phase=str_extract(OB_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(mn,by=c("novelty","afterbreak","OB_phase"))
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")

en <- pmsn %>% pivot_longer(OB_1_mean:OB_4_mean,names_to = "OB_phase",values_to = "OB_mean") %>%
  select(OB_phase,OB_mean,novelty,afterbreak) %>% mutate(OB_phase=str_extract(OB_phase,pattern = "\\w{2}_\\d"))
  
enl <- pmsn %>% pivot_longer(OB_1_sd:OB_4_sd,names_to = "OB_phase",values_to = "OB_sd") %>%
  select(OB_phase,OB_sd,novelty,afterbreak) %>% mutate(OB_phase=str_extract(OB_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(en,by=c("novelty","afterbreak","OB_phase"))
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")

## merge the exp and model result
enl$type2 = 'exp'
mnl$type2 = 'model'
allrt = rbind(enl,mnl)

ggplot(allrt,aes(x=OB_phase,y=OB_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=OB_mean-OB_sd,ymax=OB_mean+OB_sd))+facet_grid(afterbreak~type2)+
  theme_minimal()+labs(title="Experimental vs Model result")

```


```{r as}
mn <- mdn %>% pivot_longer(AS_1_mean:AS_4_mean,names_to = "AS_phase",values_to = "AS_mean") %>%
  select(AS_phase,AS_mean,novelty,afterbreak) %>% mutate(AS_phase=str_extract(AS_phase,pattern = "\\w{2}_\\d"))
  
mnl <- mdn %>% pivot_longer(AS_1_sd:AS_4_sd,names_to = "AS_phase",values_to = "AS_sd") %>%
  select(AS_phase,AS_sd,novelty,afterbreak) %>% mutate(AS_phase=str_extract(AS_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(mn,by=c("novelty","afterbreak","AS_phase"))
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")

en <- pmsn %>% pivot_longer(AS_1_mean:AS_4_mean,names_to = "AS_phase",values_to = "AS_mean") %>%
  select(AS_phase,AS_mean,novelty,afterbreak) %>% mutate(AS_phase=str_extract(AS_phase,pattern = "\\w{2}_\\d"))
  
enl <- pmsn %>% pivot_longer(AS_1_sd:AS_4_sd,names_to = "AS_phase",values_to = "AS_sd") %>%
  select(AS_phase,AS_sd,novelty,afterbreak) %>% mutate(AS_phase=str_extract(AS_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(en,by=c("novelty","afterbreak","AS_phase"))
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")

## merge the exp and model result
enl$type2 = 'exp'
mnl$type2 = 'model'
allrt = rbind(enl,mnl)

ggplot(allrt,aes(x=AS_phase,y=AS_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=AS_mean-AS_sd,ymax=AS_mean+AS_sd))+facet_grid(afterbreak~type2)+
  theme_minimal()+labs(title="Experimental vs Model result")
```




```{r dwell time}
mn <- mdn %>% pivot_longer(dwmean_1_mean:dwmean_4_mean,names_to = "dwmean_phase",values_to = "dwmean_mean") %>%
  select(dwmean_phase,dwmean_mean,novelty,afterbreak) %>% mutate(dwmean_phase=str_extract(dwmean_phase,pattern = "\\w{2}_\\d"))
  
mnl <- mdn %>% pivot_longer(dwmean_1_sd:dwmean_4_sd,names_to = "dwmean_phase",values_to = "dwmean_sd") %>%
  select(dwmean_phase,dwmean_sd,novelty,afterbreak) %>% mutate(dwmean_phase=str_extract(dwmean_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(mn,by=c("novelty","afterbreak","dwmean_phase"))
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")

en <- pmsn %>% pivot_longer(dwmean_1_mean:dwmean_4_mean,names_to = "dwmean_phase",values_to = "dwmean_mean") %>%
  select(dwmean_phase,dwmean_mean,novelty,afterbreak) %>% mutate(dwmean_phase=str_extract(dwmean_phase,pattern = "\\w{2}_\\d"))
  
enl <- pmsn %>% pivot_longer(dwmean_1_sd:dwmean_4_sd,names_to = "dwmean_phase",values_to = "dwmean_sd") %>%
  select(dwmean_phase,dwmean_sd,novelty,afterbreak) %>% mutate(dwmean_phase=str_extract(dwmean_phase,pattern = "\\w{2}_\\d")) %>%
  left_join(en,by=c("novelty","afterbreak","dwmean_phase"))
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")

## merge the exp and model result
enl$type2 = 'exp'
mnl$type2 = 'model'
allrt = rbind(enl,mnl)

ggplot(allrt,aes(x=dwmean_phase,y=dwmean_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=dwmean_mean-dwmean_sd,ymax=dwmean_mean+dwmean_sd))+facet_grid(afterbreak~type2)+
  theme_minimal()+labs(title="Experimental vs Model Dwell time")
```



```{r performance}
mnl <- mdn %>% select(performance_mean,performance_sd,novelty,afterbreak) %>% mutate(group="model")
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")
  
enl <- pmsn %>% select(performance_mean,performance_sd,novelty,afterbreak) %>% mutate(group="experiment")
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")
me <- rbind(mnl,enl)

ggplot(me,aes(x=group,y=performance_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=performance_mean-performance_sd,ymax=performance_mean+performance_sd))+facet_grid(~afterbreak)+
  theme_minimal()+labs(title="Experimental vs Model Performance")
```

```{r payoff mean}
mnl <- mdn %>% select(payoff_mean,payoff_sd,novelty,afterbreak) %>% mutate(group="model")
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")
  
enl <- pmsn %>% select(payoff_mean,payoff_sd,novelty,afterbreak) %>% mutate(group="experiment")
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")
me <- rbind(mnl,enl)

ggplot(me,aes(x=group,y=payoff_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=payoff_mean-payoff_sd,ymax=payoff_mean+payoff_sd))+facet_grid(~afterbreak)+
  theme_minimal()+labs(title="Experimental vs Model Payoff mean")
```

```{r accuracy mean}
mnl <- mdn %>% select(accuracy_mean,accuracy_sd,novelty,afterbreak) %>% mutate(group="model")
mnl$novelty <- as.factor(mnl$novelty)
levels(mnl$novelty) <- c("control","novelty")
mnl$afterbreak <- as.factor(mnl$afterbreak)
levels(mnl$afterbreak) <- c("before break","after break")
  
enl <- pmsn %>% select(accuracy_mean,accuracy_sd,novelty,afterbreak) %>% mutate(group="experiment")
enl$novelty <- as.factor(enl$novelty)
levels(enl$novelty) <- c("control","novelty")
enl$afterbreak <- as.factor(enl$afterbreak)
levels(enl$afterbreak) <- c("before break","after break")
me <- rbind(mnl,enl)

ggplot(me,aes(x=group,y=accuracy_mean,col=novelty))+geom_point()+
  geom_errorbar(aes(ymin=accuracy_mean-accuracy_sd,ymax=accuracy_mean+accuracy_sd))+facet_grid(~afterbreak)+
  theme_minimal()+labs(title="Experimental vs Model Payoff mean")
```

```{r old learning}
oldresult = read.csv("../data/archived/ppt11/allresult.csv")
oldresult = ALL.df %>% filter(Round %in% c(1,10,20,30,40))
oldresult$Round = as.factor(oldresult$Round)
ggplot(oldresult,aes(Round,performance))+
  geom_violin() +
  geom_boxplot(width=0.1)+
  labs("old model learning")
```

```{r exp painting learning}
plearn = p %>% filter(round %in% c(1,3,6,9,12,15))
plearn$round = as.factor(plearn$round)
ggplot(plearn,aes(round,performance))+
  geom_violin() +
  geom_boxplot(width=0.1)+
  labs("exp painting learning")
```

```{r}
learn = ALL.df
learn = ALL.df %>% group_by(Subject)%>%
  mutate(rk1 = ntile(Phase,6))
learn$rk1 = as.factor(learn$rk1)
learn$Phase = as.factor(learn$Phase)
oldresult = oldresult %>% filter(Round %in% c(1,10,20,30,40))
ggplot(learn,aes(Phase,performance))+
  geom_violin() +
  geom_boxplot(width=0.1)+
  labs("old model learning")
learn %>% select(Subject,Phase,rk1)
learn %>% group_by(Phase) %>%
  summarise(performance=mean(performance)) %>%
  ggplot()+
  geom_line(aes(x=Phase,y=performance))
```

```{r Use round}
rndb = read.csv("../data//newmodel//Lcontrol/all_dwsch_added.csv")
oldresult = rndb %>% filter(Round %in% c(1,5,10,15,20,15,20,25,30))
oldresult$Round = as.factor(oldresult$Round)
ggplot(oldresult,aes(Round,performance))+
  geom_violin() +
  geom_boxplot(width=0.1)+
  labs("old model learning")
```

```{r Use phase}
rndb = read.csv("../data//model_noexpfam//test/Lc//all_dwsch_added.csv")
oldresult = ALL.df %>% filter(Phase %in% c(1,5,10,15,20,15,20,25,30))
oldresult$Phase = as.factor(oldresult$Phase)
ggplot(oldresult,aes(Phase,AC))+
  geom_violin() +
  geom_boxplot(width=0.1)+
  labs("old model learning")
```